import Head from 'next/head'
import Image from 'next/image'
import { useState } from 'react'
import Intro from '../components/intro'
import SocketIO from '../components/socketio'

export default function Home() {

  return (
    <div className="h-screen flex items-center justify-center ">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Intro />
      <SocketIO />
    </div>
  )
}
